SET GLOBAL time_zone = '+03:00';

CREATE DATABASE IF NOT EXISTS mydb;
USE mydb;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    balance DECIMAL(10, 2) NOT NULL DEFAULT 0,
    last_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (balance) VALUES (1000), (2000), (500);
